config/routes.rb
Cqds::Application.routes.draw do
  get "donations/index"
  get 'test' => 'page_tab#test'
  get 'render_test' => 'heroes#render_test'
  get 'sdk' => 'sdk_test#index'
  get 'download_bizring' => 'home#download_bizring'
  get 'download_coloring' => 'home#download_coloring'
  get 'switch' => 'home#index'
  get 'please_like_this_page' => 'home#please_like_this_page'
  get 'canvas' => 'home#canvas'
  get 'game_result' => 'home#game_result'
  get 'mobile' => 'm#index'
  get 'mobile_gate' => 'm#fan_gate'
  get 'fb_login' => 'm#fb_login'
  get 'mobile_contents' => 'm#contents'
  get 'page_tab' => 'page_tab#index'
  get 'page_tab_gate' => 'page_tab#fan_gate'
  devise_for :users
  namespace :admin do
    get '/' => 'dashboard#index', ad: 'admin'
    resources :winners, only: [:index, :show]
    resources :users
    resources :donations, only: [:index, :show] do
      collection do
        get 'top_donators'
      end
    end
  end
  
  namespace :page_tab do
    resources :wall_posts, only: [:create]
  end

  namespace :m do
    resources :wall_posts, only: [:create]
    resources :users, only: [:show, :edit, :update]
  end

  resources :wall_posts, only: [:create]
  resources :users, only: [:create, :update] do
    member do 
      post :update
    end
  end
  root 'page_tab#index'  
end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true
  def self.post_message
'쿠크~ 가슴뛰는 선물!
 
지금 쿠크다스 페이지에 가서 "기부하기" 버튼만 누르면,
심장병 어린이에게 기부를! 나에게는 쿠크다스의 행운이! 
지금 참여하세요! 쿠크다스를 무료로!!   
기부하기 ▶ http://bit.ly/cqdas'
  end
  
  def self.post(user)
    api = Koala::Facebook::API.new(user.token.access_token)
    # pictures = %w(posting_img posting_01 posting_02 posting_03)
    picture = "#{Rails.root.to_s}/app/assets/images/posting_img.jpg"
    begin 
      api.put_picture(picture,"image/jpeg", {:message => WallPost.post_message})
    rescue Koala::Facebook::AuthenticationError
      Rails.logger.info "@@@@@@@@@@@@@@@@@"
      Rails.logger.info "Koala::Facebook::AuthenticationError"
      Rails.logger.info "@@@@@@@@@@@@@@@@@"
    rescue Koala::Facebook::ClientError
      Rails.logger.info "@@@@@@@@@@@@@@@@@"
      Rails.logger.info "Koala::Facebook::ClientError"
      Rails.logger.info "@@@@@@@@@@@@@@@@@"
    end
  end
  
  def self.daily_count(day)
    start_date = day.beginning_of_day
    end_date = day.end_of_day
    count = self.where("created_at >= :start_date AND created_at <= :end_date",
      {start_date: start_date, end_date: end_date}).count
  end
  
  
end

app/controllers/admin/wall_posts_controller.rb
class Admin::WallPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wall_post, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /admin/wall_posts
  # GET /admin/wall_posts.json
  def index
    @wall_posts = WallPost.order("created_at desc")
  end

  # GET /admin/wall_posts/1
  # GET /admin/wall_posts/1.json
  def show
  end

  # GET /admin/wall_posts/new
  def new
    @wall_post = WallPost.new
  end

  # GET /admin/wall_posts/1/edit
  def edit
  end

  # POST /admin/wall_posts
  # POST /admin/wall_posts.json
  def create
    @wall_post = WallPost.new(admin_wall_post_params)

    respond_to do |format|
      if @wall_post.save
        format.html { redirect_to @wall_post, notice: 'Wall post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wall_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/wall_posts/1
  # PATCH/PUT /admin/wall_posts/1.json
  def update
    respond_to do |format|
      if @wall_post.update(admin_wall_post_params)
        format.html { redirect_to @wall_post, notice: 'Wall post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/wall_posts/1
  # DELETE /admin/wall_posts/1.json
  def destroy
    @wall_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_wall_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall_post
      @wall_post = WallPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_post_params
      params[:wall_post]
    end
end

app/controllers/m/wall_posts_controller.rb
class M::WallPostsController < ApplicationController
  def create
    unless session[:facebook_uid]
      redirect_to root_path
    else
      user = User.find_by_uid(session[:facebook_uid])
      wall_post = user.wall_posts.new(wall_post_params)    
      respond_to do |format|
        if wall_post.save
          wall_post.post
          flash[:popup] = "complete"
          format.html { redirect_to mobile_path}
          format.json { render json: wall_post, status: :created, location: wall_post }
        else
          flash[:popup] = "invalid"
          format.html { redirect_to mobile_path }
          format.json { render json: wall_post.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  
  private  

    def wall_post_params
      params.require(:wall_post).permit(:message, :user_id)
    end
  
end

app/controllers/page_tab/wall_posts_controller.rb
class PageTab::WallPostsController < ApplicationController
  def create
    unless session[:facebook_uid]
      redirect_to root_path
    else
      user = User.find_by_uid(session[:facebook_uid])
      @wall_post = user.wall_posts.new(wall_post_params)    
      respond_to do |format|
        if @wall_post.save
          @wall_post.post
          flash[:popup] = "complete"
          format.html { redirect_to page_tab_path}
          format.json { render json: @wall_post, status: :created, location: @wall_post }
        else
          flash[:popup] = "invalid"
          format.html { redirect_to page_tab_path }
          format.json { render json: @wall_post.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  private  
  
    def wall_post_params
      params.require(:wall_post).permit(:message, :user_id)
      
    end
  
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  def create
    @user_agent = UserAgent.parse(request.user_agent)
    unless session[:facebook_uid]
      redirect_to root_path
    else
      user = User.find_by_uid(session[:facebook_uid])
      @wall_post = user.wall_posts.new(wall_post_params)    
      respond_to do |format|
        if @wall_post.save
          @wall_post.post
          if flash[:facebook_params].nil? or @user_agent.mobile?
            format.html { redirect_to mobile_path }
          else
            format.html { redirect_to page_tab_path }
          end
          format.json { render json: @wall_post, status: :created, location: @wall_post }
        else
          format.html { redirect_to root_path }
          format.json { render json: @wall_post.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  private  
  
    def wall_post_params
      params.require(:wall_post).permit(:message, :user_id)
    end
  
end

app/helpers/admin/wall_posts_helper.rb
module Admin::WallPostsHelper
end

app/helpers/m/wall_posts_helper.rb
module M::WallPostsHelper
end

app/helpers/page_tab/wall_posts_helper.rb
module PageTab::WallPostsHelper
end

app/views/admin/wall_posts/_form.html.erb
<%= form_for(@admin_wall_post) do |f| %>
  <% if @admin_wall_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_wall_post.errors.count, "error") %> prohibited this admin_wall_post from being saved:</h2>

      <ul>
      <% @admin_wall_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/wall_posts/edit.html.erb
<h1>Editing admin_wall_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_wall_post %> |
<%= link_to 'Back', admin_wall_posts_path %>

app/views/admin/wall_posts/index.html.erb
<div class="row-fluid">
  <!-- block -->
  <div class="block">
    <div class="navbar navbar-inner block-header">
      <div class="muted pull-left">댓글 목록</div>
    </div>
    <div class="block-content collapse in">
      <div class="span12">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data-table">
          <thead>
            <tr>
              <th>번호</th>
              <th>참여자</th>
              <th>참여 댓글</th>
            </tr>
          </thead>
          <tbody>
            <% @wall_posts.each do |wall_post| %>
              <tr class="">
                <td>
                  <% unless wall_post.user.nil? %>
                    <%= link_to(wall_post.id, "https://developers.facebook.com/tools/explorer", title: wall_post.user.uid) %>
                  <% else %>
                    <%= wall_post.id %>
                  <% end %>
                </td>
                <td>
                  <% unless wall_post.user.nil? %>
                    <%= link_to image_tag(wall_post.user.profile_image), "https://facebook.com/#{wall_post.user.uid}", target: "_blank", title: wall_post.user.token.access_token %>
                    <%= wall_post.user.name %>
                  <% end %>
                </td>
                <td class="message">
                  <p><%= wall_post.message %></p>
                  <p><%= wall_post.created_at.strftime("%m-%d") %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- /block -->
</div>

app/views/admin/wall_posts/new.html.erb
<h1>New admin_wall_post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_wall_posts_path %>

app/views/admin/wall_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_wall_post_path(@wall_post) %> |
<%= link_to 'Back', admin_wall_posts_path %>