config/routes.rb
Cqds::Application.routes.draw do
  get "donations/index"
  get 'test' => 'page_tab#test'
  get 'render_test' => 'heroes#render_test'
  get 'sdk' => 'sdk_test#index'
  get 'download_bizring' => 'home#download_bizring'
  get 'download_coloring' => 'home#download_coloring'
  get 'switch' => 'home#index'
  get 'please_like_this_page' => 'home#please_like_this_page'
  get 'canvas' => 'home#canvas'
  get 'game_result' => 'home#game_result'
  get 'mobile' => 'm#index'
  get 'mobile_gate' => 'm#fan_gate'
  get 'fb_login' => 'm#fb_login'
  get 'mobile_contents' => 'm#contents'
  get 'page_tab' => 'page_tab#index'
  get 'page_tab_gate' => 'page_tab#fan_gate'
  devise_for :users
  namespace :admin do
    get '/' => 'dashboard#index', ad: 'admin'
    resources :winners, only: [:index, :show]
    resources :users
    resources :donations, only: [:index, :show] do
      collection do
        get 'top_donators'
      end
    end
  end
  
  namespace :page_tab do
    resources :wall_posts, only: [:create]
  end

  namespace :m do
    resources :wall_posts, only: [:create]
    resources :users, only: [:show, :edit, :update]
  end

  resources :wall_posts, only: [:create]
  resources :users, only: [:create, :update] do
    member do 
      post :update
    end
  end
  root 'page_tab#index'  
end

app/controllers/m/users_controller.rb
class M::UsersController < ApplicationController
  def edit
    @user = User.find params[:id]
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to m_user_path(@user), user: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :phone_number)
  end
end

app/controllers/m/wall_posts_controller.rb
class M::WallPostsController < ApplicationController
  def create
    unless session[:facebook_uid]
      redirect_to root_path
    else
      user = User.find_by_uid(session[:facebook_uid])
      wall_post = user.wall_posts.new(wall_post_params)    
      respond_to do |format|
        if wall_post.save
          wall_post.post
          flash[:popup] = "complete"
          format.html { redirect_to mobile_path}
          format.json { render json: wall_post, status: :created, location: wall_post }
        else
          flash[:popup] = "invalid"
          format.html { redirect_to mobile_path }
          format.json { render json: wall_post.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  
  private  

    def wall_post_params
      params.require(:wall_post).permit(:message, :user_id)
    end
  
end

app/controllers/m_controller.rb
class MController < ApplicationController
  layout 'mobile'

  def index
    Rails.logger.info "@@@@@@index"
    Rails.logger.info session[:facebook_uid] unless session[:facebook_uid].nil?
    unless session[:facebook_uid].nil?
      if check_like == true
        Rails.logger.info "@@@@@@ go to mobile_path"
        @user = current_user
      else
        Rails.logger.info "@@@@@@ go to mobile_gate_path"
        redirect_to mobile_gate_path
      end
    else
      redirect_to fb_login_path
    end
  end
  
  def fb_login
    Rails.logger.info "@@@@@@fb_login"
    Rails.logger.info session[:facebook_uid] unless session[:facebook_uid].nil?
    unless session[:facebook_uid].nil?
      if check_like == true
        Rails.logger.info "@@@@@@ go to mobile_path"
        redirect_to mobile_path
      else
        Rails.logger.info "@@@@@@ go to mobile_gate_path"
        redirect_to mobile_gate_path
      end
    else
      render :layout => false
    end    
  end
  
  def fan_gate
    Rails.logger.info "@@@@@@fan_gate"
    Rails.logger.info session[:facebook_uid] unless session[:facebook_uid].nil?
    unless session[:facebook_uid].nil?
      if check_like == true
        Rails.logger.info "@@@@@@ go to mobile_path"
        redirect_to mobile_path
      else
        if check_like == "auth error"
          redirect_to fb_login_path
        else
          Rails.logger.info "@@@@@@ go to mobile_gate_path"
        end
      end
    else
      redirect_to fb_login_path
    end    
    
  end
  
  private
    def check_like
      page_id = FACEBOOK_CONFIG[:page_id]
      Rails.logger.info("%%%page id: "+page_id)
      token = current_user.token.access_token
      # access_token = session[:facebook_token]
      api = Koala::Facebook::API.new(token)
      result = false
      begin
        query = api.get_connections("me","likes/" + page_id)
      rescue Koala::Facebook::AuthenticationError
        Rails.logger.info "auth error!! uid: " + session[:facebook_uid]
        session[:facebook_uid] = nil
        # redirect_to fb_login_path
        query = "auth error"
      rescue Koala::Facebook::ClientError
        Rails.logger.info "client error!! uid: " + session[:facebook_uid]
        session[:facebook_uid] = nil
        query = []
      end
      result = true unless query.empty?
      result = "auth error" if query == "auth error"
      Rails.logger.info "@@@@@check_like@@@@"
      Rails.logger.info result
      Rails.logger.info "@@@@@@@@@"
      return result
    end
        
end

app/helpers/m/users_helper.rb
module M::UsersHelper
end

app/helpers/m/wall_posts_helper.rb
module M::WallPostsHelper
end

app/helpers/m_helper.rb
module MHelper
end

app/views/m/fan_gate.html.erb
<div class="like_wrap">
  <%= image_tag "page_tab/CQDS_Mobile/shield_top.png"%>
  <div class="like_button" id="like_button">
    <fb:like href="<%= FACEBOOK_CONFIG[:page_address]%>" colorscheme="light" layout="button_count" action="like" show_faces="false" send="false"></fb:like>
  </div>
  <%= image_tag "page_tab/CQDS_Mobile/shield_bottom.png"%>
</div>

app/views/m/fb_login.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#" xmlns:og="http://ogp.me/ns#">
<head prefix="og: http://ogp.me/ns#">
  <title>쿠크다스 로그인</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    "mobile", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "mobile", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Description Here" />
  <meta property="fb:app_id" content="<%= FACEBOOK_CONFIG[:app_id] %>" />
  <meta property="og:type"   content="myapp:myobject" />
</head>
<body id="mobile">
  <div id="fb-root"></div>
<script type="text/javascript">
function spin(){
  var opts = {
    lines: 13, // The number of lines to draw
    length: 20, // The length of each line
    width: 10, // The line thickness
    radius: 30, // The radius of the inner circle
    corners: 1, // Corner roundness (0..1)
    rotate: 0, // The rotation offset
    direction: 1, // 1: clockwise, -1: counterclockwise
    color: '#000', // #rgb or #rrggbb or array of colors
    speed: 1, // Rounds per second
    trail: 60, // Afterglow percentage
    shadow: false, // Whether to render a shadow
    hwaccel: false, // Whether to use hardware acceleration
    className: 'spinner', // The CSS class to assign to the spinner
    zIndex: 29, // The z-index (defaults to 2000000000)
    left: 48-60, // Left position relative to parent in px
    top: 22-60 // Top position relative to parent in px
  };
  var target = document.getElementById('join');
  var spinner = new Spinner(opts).spin(target);
};

function reload(){
  location.reload();
};
function login(response){
  spin();
  var uid = response.authResponse.userID;
  var accessToken = response.authResponse.accessToken;
  $.ajax({
    type: "POST",
    url: "/users",
    data: {uid: uid, access_token: accessToken, test: "test"},
    headers: {
      'X-Transaction': 'POST Example',
      'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
    },
    success: reload
  });
};

var cb = function(response){
  if (response.status === 'connected') {
    login(response);
  } else if (response.status === 'not_authorized') {
    alert('캠페인 참여를 위해 페이스북 로그인이 필요합니다.');
  } else {
    alert('페이스북 로그인이 필요합니다.');
  }
};

function fb_auth(e){
  e.preventDefault();
  FB.getLoginStatus(function(response) {
    if (response.status === 'not_authorized') {
      FB.login(cb,{
        scope: 'email, user_birthday, user_photos, publish_stream'
      });
      login(response);
    }else if (response.status === 'connected'){
      login(response);
    }else{
      FB.login(cb,{
        scope: 'email, user_birthday, user_photos, publish_stream'
      });
      login(response);
    }
  });
};

$(document).ready(function() {
  $.ajaxSetup({ cache: true });
  $.getScript('//connect.facebook.net/ko_KR/all.js', function(){
    FB.init({
      appId      : '<%= FACEBOOK_CONFIG[:app_id] %>',     // App ID from the appdashboard
      channelUrl : '//<%= FACEBOOK_CONFIG[:domain] %>/channel.html', // Channel file for x-domain comms
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
    
    $('#join').bind('click', function(e) {
      
      fb_auth(e);
    });
  });
});

</script>
  <%= link_to image_tag("page_tab/CQDS_Mobile/mobile_login_button.png"), nil, title: "join", id: "join" %>
</body>
</html>

app/views/m/index.html.erb
<script type="text/javascript">
  function changeFocus(pos) {
  	if(pos==1) { 
  		document.getElementById("youtube").src="//www.youtube.com/embed/hAa0OTP9eWE?wmode=opaque" ;
  		document.getElementById("youtube_01").src='<%= asset_path("page_tab/CQDS_Mobile/tvcf_c.png") %>' ;
    	document.getElementById("youtube_02").src='<%= asset_path("page_tab/CQDS_Mobile/interview.png") %>' ;
    }
    else if(pos==2) {
    	document.getElementById("youtube").src="//www.youtube.com/embed/EYhliYh3fC4?wmode=opaque" ;
    	document.getElementById("youtube_01").src='<%= asset_path("page_tab/CQDS_Mobile/tvcf.png") %>' ;
    	document.getElementById("youtube_02").src='<%= asset_path("page_tab/CQDS_Mobile/interview_c.png") %>' ;
  	}
  }
</script>
<style>
.modal_fail {
  opacity:1.0;
  width: 579px; 
  height: 364px;
  display: none;
  background: url('<%= asset_path("page_tab/CQDS_M/Popup/back.png") %>') no-repeat 0 0;
  -webkit-border-radius: 8px;
  -moz-border-radius: 8px;
  -o-border-radius: 8px;
  -ms-border-radius: 8px;
  border-radius: 8px;
  -webkit-box-shadow: 0 0 10px #000;
  -moz-box-shadow: 0 0 10px #000;
  -o-box-shadow: 0 0 10px #000;
  -ms-box-shadow: 0 0 10px #000;
  box-shadow: 0 0 10px #000;

  /* Double-sized Checkboxes */
  -ms-transform: scale(0.5); /* IE */
  -moz-transform: scale(0.5); /* FF */
  -webkit-transform: scale(0.5); /* Safari and Chrome */
  -o-transform: scale(0.5); /* Opera */
  
 }
.modal_limit {
 opacity:1.0;
 width: 500px; 
 height: 245px;
 display: none;
 background: url('<%= asset_path("page_tab/CQDS_M/Popup_limit/limit.png") %>') no-repeat 0 0;
 -webkit-border-radius: 8px;
 -moz-border-radius: 8px;
 -o-border-radius: 8px;
 -ms-border-radius: 8px;
 border-radius: 8px;
 -webkit-box-shadow: 0 0 10px #000;
 -moz-box-shadow: 0 0 10px #000;
 -o-box-shadow: 0 0 10px #000;
 -ms-box-shadow: 0 0 10px #000;
 box-shadow: 0 0 10px #000;

 /* Double-sized Checkboxes */
 -ms-transform: scale(0.5); /* IE */
 -moz-transform: scale(0.5); /* FF */
 -webkit-transform: scale(0.5); /* Safari and Chrome */
 -o-transform: scale(0.5); /* Opera */

}
.modal_congratulation {
 opacity:1.0;
 width: 500px; 
 height: 245px;
 display: none;
 background: url('<%= asset_path("page_tab/CQDS_M/Popup_congratulation/pop_congratulation.png") %>') no-repeat 0 0;
 -webkit-border-radius: 8px;
 -moz-border-radius: 8px;
 -o-border-radius: 8px;
 -ms-border-radius: 8px;
 border-radius: 8px;
 -webkit-box-shadow: 0 0 10px #000;
 -moz-box-shadow: 0 0 10px #000;
 -o-box-shadow: 0 0 10px #000;
 -ms-box-shadow: 0 0 10px #000;
 box-shadow: 0 0 10px #000;

 /* Double-sized Checkboxes */
 -ms-transform: scale(0.5); /* IE */
 -moz-transform: scale(0.5); /* FF */
 -webkit-transform: scale(0.5); /* Safari and Chrome */
 -o-transform: scale(0.5); /* Opera */

}
 
 
.modal_start {
  opacity:1.0; 
  width: 579px; 
  height: 537px;
  display: none;
  background: url('<%= asset_path("page_tab/CQDS_M/Popup2/back.png") %>') no-repeat 0 0;
  -webkit-border-radius: 8px;
  -moz-border-radius: 8px;
  -o-border-radius: 8px;
  -ms-border-radius: 8px;
  border-radius: 8px;
  -webkit-box-shadow: 0 0 10px #000;
  -moz-box-shadow: 0 0 10px #000;
  -o-box-shadow: 0 0 10px #000;
  -ms-box-shadow: 0 0 10px #000;
  box-shadow: 0 0 10px #000;
  /* Double-sized Checkboxes */
  -ms-transform: scale(0.5); /* IE */
  -moz-transform: scale(0.5); /* FF */
  -webkit-transform: scale(0.5); /* Safari and Chrome */
  -o-transform: scale(0.5); /* Opera */
  
 } 
 
.modal_success {
  opacity:1.0; 
  width: 564px; 
  height: 882px;
  display: none;
  background: url('<%= asset_path("page_tab/CQDS_M/Popup3/back.png") %>') no-repeat 0 0;
  -webkit-border-radius: 8px;
  -moz-border-radius: 8px;
  -o-border-radius: 8px;
  -ms-border-radius: 8px;
  border-radius: 8px;
  -webkit-box-shadow: 0 0 10px #000;
  -moz-box-shadow: 0 0 10px #000;
  -o-box-shadow: 0 0 10px #000;
  -ms-box-shadow: 0 0 10px #000;
  box-shadow: 0 0 10px #000;

  /* Double-sized Checkboxes */
  -ms-transform: scale(0.5); /* IE */
  -moz-transform: scale(0.5); /* FF */
  -webkit-transform: scale(0.5); /* Safari and Chrome */
  -o-transform: scale(0.5); /* Opera */

 }  
 

</style>
<div class="header">
  <%= image_tag "page_tab/CQDS_Mobile/1.png", class: "header" %>
</div>

<div class="mobile2-1">
	<img src='<%= asset_path("page_tab/CQDS_Mobile/2-1.png") %>'/>
</div>
<div class="mobile2-2" style="width: 100%;" >
	<table>
		<tr>
			<td> <img id='youtube_01' src='<%= asset_path("page_tab/CQDS_Mobile/tvcf_c.png") %>' onclick='changeFocus(1)'; style="width: 100%; max-width: 320px;"></td>
			<td> <img id='youtube_02' src='<%= asset_path("page_tab/CQDS_Mobile/interview.png")  %>'onclick='changeFocus(2)' style="width: 100%; max-width: 320px;"</td>
		</tr>
	</table>
</div> 
<div class="mobile2-3">
	<img src='<%= asset_path("page_tab/CQDS_Mobile/2-3.png") %>'/>
</div>
<div style="width: 100%;">
  <div class="mobile3">
		<iframe id="youtube" src="//www.youtube.com/embed/hAa0OTP9eWE?wmode=opaque" frameborder="0" allowfullscreen ></iframe> 
  </div>
</div>


<div class="mobile4-1">
	<img src='<%= asset_path("page_tab/CQDS_Mobile/4-1.png") %>'/>
</div>
<div class="mobile4-2" style="width: 100%;" >
	<table>
		<tr>
			<td>
        <img src='<%= asset_path("page_tab/CQDS_Mobile/4-2-1.png") %>' />
      </td>
			<td id="donation_panel"> 
        <a href="#" id="event_popup"> 
          <img src='<%= asset_path("page_tab/CQDS_Mobile/4-2-2.png") %>'>
        </a> 
      </td>
			<td> 
        <img src='<%= asset_path("page_tab/CQDS_Mobile/4-2-3.png") %>'>
      </td>
		</tr>
	</table>
</div> 
<div class="mobile4-3">
  <p id="total_donations" class="donation_count">
    현재 5,000,000원 적립
  </p>
</div>
<% user_agent = UserAgent.parse(request.user_agent) %>
<% unless user_agent.platform == "iPhone" %>
<div class="mobile5">
	<table>
		<tr>
			<td> 
        <a href="<%= download_coloring_path %>" class="coloring">
          <%= image_tag("page_tab/CQDS_Mobile/5-1.png", class:"coloring_link") %>
        </a>
      </td>
			<td>
        <a href="<%= download_bizring_path %>" class="alram">
          <%= image_tag("page_tab/CQDS_Mobile/5-2.png", class:"coloring_link") %>
        </a>
      </td>
		</tr>
	</table>
</div>
<% end %>
<div class="mobile6">
	<img src='<%= asset_path("page_tab/CQDS_Mobile/6.png") %>'/>
</div>


<div id="pop_start" class="modal_start" style="display:none;">
	<a href="#" rel="modal:close">
    <img width="58" height="56" src='<%= asset_path("page_tab/CQDS_M/Popup2/close.png") %>'style="float:right;"/>
  </a>
	<div class="popup2_check">
		<a href="#" id="game_result" >
      <%= image_tag "page_tab/CQDS_M/Popup2/check.png" %>
    </a> 	
	</div>	
</div>

<div id="pop_fail" class="modal_fail" style="display:none;">
	<a href="#" rel="modal:close">
    <img width="58" height="56" src='<%= asset_path("page_tab/CQDS_M/Popup/close.png") %>'style="float:right;">
  </a>
	<div class="popup1_check">
		<a href="#" rel="modal:close" >
      <%= image_tag "page_tab/CQDS_M/Popup/check.png" %>
    </a> 	
	</div>	
</div>
<div id="pop_limit" class="modal_limit" style="display:none;">
	<a href="#" rel="modal:close">
    <% image_tag "page_tab/CQDS_M/Popup2/close.png", class: "popup_close" %>
  </a>
	<div class="popup_limit_check">
		<a href="#" rel="modal:close">
      <%= image_tag "page_tab/CQDS_M/Popup_limit/check.png" %>
    </a> 	
	</div>	
</div>
<div id="pop_congratulation" class="modal_congratulation" style="display:none;">
	<a href="#" rel="modal:close">
    <% image_tag "page_tab/CQDS_M/Popup2/close.png", class: "popup_close" %>
  </a>
	<div class="popup_limit_check">
		<a href="#" rel="modal:close">
      <%= image_tag "page_tab/CQDS_M/Popup_congratulation/check.png" %>
    </a> 	
	</div>	
</div>

<div id="pop_success" class="modal_success" style="display:none;">
	<a href="#" rel="modal:close">
    <img width="58" height="56" 
    src='<%= asset_path("page_tab/CQDS_M/Popup3/close.png") %>' style="float:right;"/>
  </a>
  <%= simple_form_for @user, html: {id: "edit_winner"} do |f| %>
    <%= f.input :uid, as: :hidden, value: @user.uid %>
    <%= hidden_field_tag :access_token, value: @user.token.access_token unless @user.token.nil? %>
  	<div class="name">
      <%= f.input :name, input_html: {style: "padding: 2px 2px 2px 2px; width:242px; height:46px; font-size:13pt;"}, label: false %>
  	</div>
  	<div class="phone">
  		<ul class="phone_ul">
  				<li class="phone_first"> 
            <input type="text" id="phone1" name="phone1"  onKeyPress="if ((event.keyCode < 48) || (event.keyCode > 57)){event.returnValue = false;};" maxlength="4"> 
          </li> 
  				<li class="phone_middle"> 
            <input type="text" id="phone2" name="phone2" onKeyPress="if ((event.keyCode < 48) || (event.keyCode > 57)){event.returnValue = false;};" maxlength="4" style=""> 
          </li>
  				<li class="phone_last">   
            <input type="text" id="phone3" name="phone3" onKeyPress="if ((event.keyCode < 48) || (event.keyCode > 57)){event.returnValue = false;};" maxlength="4" style="">
          </li>
  		</ul>
  	</div>
  	<div class="check">
  		<ul class="check_ul">
  			<li class="check_agree"> 
          <input type="checkbox" name="user_info_check" class="info_check" value="agree" style="width:18px; height:18px;"> 
        </li>
  			<li class="provision">
          <a href="https://www.crown.co.kr/member/pop_private.asp" target="_blank">
            <%= image_tag("page_tab/CQDS_M/Popup3/content.png") %>
          </a>
        </li>
  		</ul>
  	</div>
  	<div class="popup3_check">
      <%= image_submit_tag("page_tab/CQDS_M/Popup3/check.png", class: "button", id: "winner_submit") %>
  	</div>	
  <% end %>
</div>
<!-- <fb:like href="<%= FACEBOOK_CONFIG[:page_address]%>" colorscheme="light" layout="button_count" action="like" show_faces="false" send="false"></fb:like> -->