config/routes.rb
Cqds::Application.routes.draw do
  get "donations/index"
  get 'test' => 'page_tab#test'
  get 'render_test' => 'heroes#render_test'
  get 'sdk' => 'sdk_test#index'
  get 'download_bizring' => 'home#download_bizring'
  get 'download_coloring' => 'home#download_coloring'
  get 'switch' => 'home#index'
  get 'please_like_this_page' => 'home#please_like_this_page'
  get 'canvas' => 'home#canvas'
  get 'game_result' => 'home#game_result'
  get 'mobile' => 'm#index'
  get 'mobile_gate' => 'm#fan_gate'
  get 'fb_login' => 'm#fb_login'
  get 'mobile_contents' => 'm#contents'
  get 'page_tab' => 'page_tab#index'
  get 'page_tab_gate' => 'page_tab#fan_gate'
  devise_for :users
  namespace :admin do
    get '/' => 'dashboard#index', ad: 'admin'
    resources :winners, only: [:index, :show]
    resources :users
    resources :donations, only: [:index, :show] do
      collection do
        get 'top_donators'
      end
    end
  end
  
  namespace :page_tab do
    resources :wall_posts, only: [:create]
  end

  namespace :m do
    resources :wall_posts, only: [:create]
    resources :users, only: [:show, :edit, :update]
  end

  resources :wall_posts, only: [:create]
  resources :users, only: [:create, :update] do
    member do 
      post :update
    end
  end
  root 'page_tab#index'  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable  
  include DailyCount
  has_one :token, as: :identifiable
  has_many :donations
  scope :top_donator, order('donations_count DESC')

  
  def daily_donations(day)
    start_date = day.beginning_of_day
    end_date = day.end_of_day
    count = self.donations.where("created_at >= :start_date AND created_at <= :end_date",
      {start_date: start_date, end_date: end_date}).count
  end
  
  def self.create_or_find_fan!(uid, access_token)
    unless exists?(uid: uid)
      fan = User.new
      Token.create_or_update_token!(fan, access_token)
      fan.uid = uid
      fan.detail_from_facebook(access_token)
      fan.save
    else
      fan = find_by_uid(uid)
      Token.create_or_update_token!(fan, access_token)
      fan.detail_from_facebook(access_token)
      fan.save
    end
    fan
  end
  
  def detail_from_facebook(access_token)
    graph = Koala::Facebook::API.new(access_token)
    profile = graph.get_object("me")
    relationship = graph.fql_query("SELECT relationship_status  FROM user where uid=me()") 
    self.name = profile["name"]
    self.gender = profile["gender"]
    self.age = profile["birthday"]
    self.location = profile["location"]["name"] unless profile["location"].nil?
    self.profile_image = graph.get_picture(profile["id"])
    self.relationship = relationship.first["relationship_status"]
  end  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  before_action :set_user, only: [:show, :edit, :update, :show]
  
  def index
    @users = User.order("created_at desc").page(params[:page]).per(2000)
  end

  def show
    
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end  
    
    def user_params
      params.require(:user).permit(:id, :email, :phone, :password, :name, :phone, :uid)
    end
end

app/controllers/m/users_controller.rb
class M::UsersController < ApplicationController
  def edit
    @user = User.find params[:id]
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to m_user_path(@user), user: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :phone_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  

  def create
    uid = params["uid"]
    access_token = params["access_token"]
    user = User.create_or_find_fan!(uid, access_token)
    session[:facebook_uid] = uid
    session[:facebook_token] = access_token
    Donation.registering(user)
    total_donations = Donation.count * 100
    date = DateTime.parse("2014-02-28 19:59:59 +0900")
    if Time.now < date
      today_limit = user.daily_donations(Time.now)
    else
      today_limit = "timeover"
    end
    total_donations = view_context.number_with_delimiter(total_donations)
    data = {total_donations: total_donations, today_limit: today_limit}
    
    
    respond_to do |format|
      format.html {render nothing: true}
      format.json {render json: data}
    end
  end
  
  def update
    @user = User.find_by_uid params[:id]
    @user.update(user_params)
    render nothing: true
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:id, :uid, :name, :email, :phone_number, :password, :data)
  end
end

app/helpers/m/users_helper.rb
module M::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="row-fluid">
  <!-- block -->
  <div class="block">
    <div class="navbar navbar-inner block-header">
      <div class="muted pull-left">회원 정보 수정</div>
    </div>
    <div class="block-content collapse in">
      <div class="span12">

<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>기본정보</legend>
    <div class="control-group">
      <label class="control-label" for="focusedInput">이름</label>
      <div class="controls">
        <%= f.text_field :name, id: "focusedInput", class: "input-xlarge focused"%>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">이메일</label>
      <div class="controls">
        <%= f.text_field :email, class: "input-xlarge focused"%>
      </div>
    </div>
    <% if controller.action_name == "new" %>
    <div class="control-group">
      <label class="control-label">비밀번호</label>
      <div class="controls">
        <%= f.password_field :password, class: "input-xlarge focused"%>
        <span class="help-inline">비번은 8자 이상</span>
      </div>
    </div>
    <% end %>
    <div class="control-group">
      <label class="control-label">페이스북 주소</label>
      <div class="controls">
        <%= f.text_field :uid, class: "input-xlarge focused", placeholder: "예)http://facebook.com/onesup"%>
        <span class="help-inline">페이스북 로그인을 위해 반드시 필요.</span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">전화번호</label>
      <div class="controls">
        <%= f.text_field :phone_number, class: "input-xlarge focused"%>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit class: "btn btn-primary"  %>
      <%= link_to "취소", admin_path, class: "btn"%>
    </div>
  </fieldset>

<% end %>
      </div>
    </div>
  </div>
  <!-- /block -->
</div>

app/views/admin/users/index.html.erb
<div class="row-fluid">
  <!-- block -->
  <div class="block">
    <div class="navbar navbar-inner block-header">
      <div class="muted pull-left">참여자 목록</div>
    </div>
    <div class="block-content collapse in">
      <div class="span12">
        <%= paginate @users %>
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data-table">
          <thead>
            <tr>
              <th>번호</th>
              <th>참여자</th>
              <th>생년월일</th>
              <th>지역</th>
              <th>타고온 곳</th>
              <th>참여일시</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr class="">
                <td>
                  <%= link_to(user.id, nil, title: user.uid) %>
                </td>
                <td>
                  <%= link_to image_tag(user.profile_image), "https://facebook.com/#{user.uid}", target: "_blank" %>
                  <%= user.name %>
                </td>
                <td>
                  <%= user.age unless user.age.nil? %>
                </td>
                <td>
                  <%= user.location unless user.location.nil? %>
                </td>
                <td>
                  <%= user.data unless user.data.nil? %>
                </td>
                <td class="updated_at">
                  <p><%= user.updated_at.strftime("%m.%d %H:%M:%S") %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
  <!-- /block -->
</div>

app/views/admin/users/show.html.erb
<div class="row-fluid">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left">"<%= @user.email %>" 회원 정보 보기</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                 <form class="form-horizontal">
                  <fieldset>
                    <legend>기본정보</legend>
                    <div class="control-group">
                      <label class="control-label" for="focusedInput">이름</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @user.name %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">이메일</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @user.email %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">전화번호</label>
                      <div class="controls">
                        <span class="input-xlarge uneditable-input"><%= @user.phone_number %></span>
                      </div>
                    </div>
                    <div class="control-group">
                      <label class="control-label">페이스북 아이디</label>
                      <div class="controls">
                        <%= link_to "https://facebook.com/#{@user.uid}", "https://facebook.com/#{@user.uid}", target: "_blank" %></span>
                      </div>
                    </div>

                    <div class="control-group">
                      <label class="control-label">가입일시</label>
                      <div class="controls">
                        <span class=""><%= @user.created_at %></span>
                      </div>
                    </div>

                    <div class="form-actions">
                      <%= link_to "정보수정", edit_admin_user_path(@user), class: "btn btn-primary"%>
                      <!-- <button type="submit" class="btn btn-primary">Modify</button> -->
                      <%= link_to "사용자 전체 목록", admin_users_path, class: "btn"%>
                    </div>
                  </fieldset>
                </form>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>